version: "3"
services:
    mysql:
        image: mysql:5.7
        ports:
            - "3266:3266"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        image: wordpress:latest
        ports:
            - "2000:80"
        volumes:
            - mywebsite_data:/var/www/html
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

        depends_on: 
            - mysql
        links:
            - mysql

volumes:
    mysql_data:
    mywebsite_data:
